### PR TITLE
Readme updates

### PR DESCRIPTION
**Pull request by lyzidiamond**
- Changes Leaflet.js to Mapbox.js in readme (you're using Mapbox.js)
- Grammar edits

### CODE REVIEW

**Comment by svmatthews** [comment]
Truth, but we're relying heavily on the Leaflet architecture. What's the best way to specify? Is using Mapbox.js necessary?

**Comment by lyzidiamond** [comment]
It's just the reality. Mapbox.js is a Leaflet.js plugin. By saying you're using Mapbox.js, it's implied that you're using Leaflet.js, because the two can't really be decoupled.

**Comment by svmatthews** [comment]
:dancer: thanks for the clarification! It seems like it will be useful to continue with Mapbox.js since that gives us access to a suite of tools that will likely be used in the future.

**Comment by lyzidiamond** [comment]
Thinking about it a little more... I think there's room for an **About** that explains how the application works w/r/t Leaflet's architecture. Let's talk about it more when we meet to chat about `CONTRIBUTING.md` @svmatthews

**Comment by svmatthews** [comment]
:+1:

**Pull request merged**
