### PR TITLE
Remove python dep

### PR DESCRIPTION
**Pull request by knownasilya**
Make running this super easy, no python to worry about.

### CODE REVIEW

**Comment by svmatthews** [comment]
Hey! Thanks for setting this up. Two things:

1. Right now if the server exists at `.../app` level there is no access to the root level `/bower_components/` directory. I like the idea that the user doesn't need to run it at `/app` though, so maybe we should set up a [`.bowerrc`](http://bower.io/docs/config/) file. I wonder how that works with `wiredep`?
2. Any interest in figuring out how to properly set this up to run with grunt `watch`? Relates to #9

**Comment by knownasilya** [comment]
> Right now if the server exists at `.../app`

Can you explain what you mean by this statement?

**Comment by svmatthews** [comment]
Yes of course. Since the server is being set within the `/app` directory via [this parameter](https://github.com/knownasilya/drop-n-chop/commit/f5d6d92985e0246330d98bede5d0e44517674ecd#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R13), the paths to the necessary vendor libraries (i.e. jQuery, turf, mapbox.js) are broken and do not load. This is a result of the `/bower_components` library being one level above the server and therefore inaccessible.

Here's an image of the console errors I'm seeing:
screen shot 2015-03-30 at 10 25 03 am

I think the best fix here would be to move the `/bower_components` into the `/app` directory (i.e. `/app/bower_components` or `/app/static/lib`) using the `.bowerrc` option.

**Comment by knownasilya** [comment]
Seems to be working fine, on my end. I did `npm start` in the main directory and opened `localhost:8000`.

screen shot 2015-03-30 at 1 33 30 pm

**Comment by svmatthews** [comment]
Hmm, I honestly don't know what's going on! I've run `npm install` and `bower install` and `npm start` and am still getting the errors. Any ideas?

**Comment by knownasilya** [comment]
Try doing `rm -rf node_modules && npm cache clean && npm install`

**Comment by svmatthews** [comment]
Didn't work for me :(

**Comment by svmatthews** [comment]
I'm wondering if it would be best to use the `.bowerrc` file and do this through `grunt serve` instead, just to keep everything under the same task runner?

**Comment by alukach** [comment]
I think the problem is that `goat` is only serving `app`.  This fix did it for me: https://github.com/knownasilya/drop-n-chop/pull/1

Side note: I did a PR to the PR, which is a bit weird. Felt that seemed a bit more sensible than creating a new PR. :confused:

**Comment by knownasilya** [comment]
@alukach it still doesn't explain why it works on my end :smile:

I think PRs on PRs is a good thing :+1:

**Comment by knownasilya** [comment]
@svmatthews give that a try.

**Comment by alukach** [comment]
@knownasilya Yeah, I'm unsure how it could have worked for you. Are you sure that your browser wasn't serving cached data from `/bower_components`?  I was able to reproduce @svmatthews issue.  When I would attempt to access `http://localhost:8000/bower_components/turf/turf.min.js`, I would get a 404.

To speak more on this topic, `goat` seems to work but it seems to be lacking a `--reload` option to reboot the server on code changes.  It's an improvement over the python server but I think #9 would still be advantageous.

**Comment by knownasilya** [comment]
@alukach I'm thinking of adding a `--live-reload` option to `goat`, basically would serve a live-reload script. You'd have to add the script src to index.html though.

**Comment by knownasilya** [comment]
Although I'm a bit on the side of this being a none dev implementation since it uses `npm start`. I'd want to see live-reload only for those developing this, which means they'd be using grunt.

**Comment by alukach** [comment]
I'm not super familiar with JS projects but I think the oddities are coming around how the project is structured.

```
app/
  - css/
    - app.css
  - js/
    - app.js
  - index.html
bower_components/
  - jquery/
  - ...
````

Something feels a bit odd about this.  `index.html` points to the `bower_components` assets as if they live within it's parent directory:

```html
  <script src="../bower_components/jquery/dist/jquery.js"></script>
  <script src="../bower_components/turf/turf.min.js"></script>
  <script src="../bower_components/mapbox.js/mapbox.js"></script>
```

This works if `index.html` is at the path root, where `../bower_components == ./bower_components`.  I think the correct solution (for now) is to instruct `bower` to install all of it's dependencies into `app/static/bower_components`.  This way only a single directory needs to be served. 

See https://github.com/knownasilya/drop-n-chop/pull/2

**Comment by alukach** [comment]
>  I'd want to see live-reload only for those developing this, which means they'd be using grunt.

I'm a bit confused by this.  I would imagine that the only people running `npm start` would be devs. What is the envisioned deployment of this project?  I assumed it would be hosted somewhere, allowing anyone with an internet connection to use it (rather than requiring them to download/run locally).

**Comment by knownasilya** [comment]
There are really two options:

1. Serve this as static data in nginx directly
2. Serve this via a node server (goat) and proxy via nginx

Usually node related web apps go with route 2.

**Comment by alukach** [comment]
Why stop there?

1. Serve this as static data in nginx directly
2. Serve this via a node server (goat) and proxy via nginx
3. Serve via Github Pages
4. Serve via Amazon S3.

Seeing as this is all static, I would push for 3 or 4, as they involve less moving parts.  I don't really think of this project as being node related, rather it uses node to help generate the static content (similar to Ruby's involvement in any Jekyll site).

**Comment by knownasilya** [comment]
True (plus a dozen other ways).

Live Reload has it's place, but that should probably be addressed in a different PR.

**Comment by svmatthews** [comment]
Thanks for the conversation @alukach and @knownasilya! It seems best at this point to figure out how devs can run their own local server easily and focusing on how to deploy later once there is a fully-functioning alpha version. The plan is to have this running as a web-app and not for people to download themselves (that's kind of the reason why the project started :smile:). 

I'm a fan of `node_components` existing within the `/app` directory right now - seems to make the most sense to me. How about creating a new issue in regards to how to serve this in production?

**Comment by svmatthews** [comment]
Working great after trying the new updates on my end! Looks like an update to the `.gitignore` bower components is all that is left.

**Comment by knownasilya** [comment]
@svmatthews all set

**Comment by alukach** [comment]
Not to be overly concerned with details, but changing gitignore from `bower_components/` to `app/static/bower_components` is actually more specific. If left at `bower_components/` [any directory named `bower_components/` would be ignored](http://stackoverflow.com/questions/1470572/gitignore-ignore-any-bin-directory) (not just that at the project root).  Is this the intention?

**Comment by svmatthews** [comment]
Thanks @knownasilya & @alukach!

**Pull request merged**
