### PR TITLE
add intersect function

### PR DESCRIPTION
**Pull request by hamhands**
### What changed
* Added intersect function to handlers and ops in menu.js
* Implements changes started in #26

### CODE REVIEW

**Comment by svmatthews** [comment]
closing #26 in favor of this PR

**Comment by alukach** [comment]
So, I think there's some good news and some bad news related to this PR.

The bad news is that, after the #30 merge, this PR is no longer compatible.  The way that the menus and operations are constructed is now very different (and largely abstracted).  This means that this change will probably not be accepted.

The good news is that it's now easy-peasy to add support for Turf operations.  All you need to do is add a new configuration in the [MenuBar.js](https://github.com/cugos/drop-n-chop/blob/6bcafaf6b17955c0f291b1909835c586a5536525/src/js/menu/MenuBar.js#L15-L18) indicating which Turf operation you're adding and what the requirements for the operation are.  It should now be super easy to add a ton of the Turf.js operations today, and we'll build out the `TurfOperation` class to accommodate those that aren't supported yet.

Is there any point to keep this PR open or we should try again for a third one?

**Comment by svmatthews** [comment]
Oh man you may have just broken @hamhands's :heart: - I was so confident in his addition and totally blanked on the incoming changes. I'll work with him tomorrow on rebasing this PR and incorporating the new updates. No need to close!

**Comment by hamhands** [comment]
It's cool guys, I got this:
tumblr_mnb4mzxm6j1rks8b7o1_500

**Comment by svmatthews** [comment]
luxk2be

**Comment by svmatthews** [comment]
Sorry @hamhands gotta close this in prep for our sprint next week!

**Pull request closed without merging**
