### PR TITLE
No longer store dist/ in repo

### PR DESCRIPTION
**Pull request by alukach**
As per #32

### CODE REVIEW

**Comment by svmatthews** [comment]
Thanks for doing this! Looks like Travis is running off of `/dist`, which may make testing a bit more complicated. Might need to have @thebigspoon chime in on this one.

**Comment by alukach** [comment]
@svmatthews Okay, this should be good to go now!

**Comment by svmatthews** [comment]
:+1:

**Comment by svmatthews** [comment]
:+1:

**Pull request merged**
